name: Linux-Windows cross-compile

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Add rust target
        run: |
          rustup target add x86_64-pc-windows-gnu
      - name: Install dependencies
        run: |
          sudo apt-get -y install clang gcc-mingw-w64-x86-64 libclang-dev
      - name: Build
        run: cargo build --verbose --target=x86_64-pc-windows-gnu --features=all
