name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup SocketCAN
      run: |
        sudo apt-get -y install linux-modules-extra-$(uname -r) can-utils
        pip install --user scapy
        scripts/build_can_isotp.sh
        scripts/set_up_vcan.sh
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --features=test_vcan --verbose
